// 把 server + core 打成一个 ESM bundle（原生模块保持 external），供 Electron 主进程 import。
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { copyFileSync } from "node:fs";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..");

await build({
  entryPoints: [join(repoRoot, "apps", "server", "src", "server.ts")],
  outfile: join(here, "build", "server.mjs"),
  bundle: true, platform: "node", format: "esm", target: "node20",
  sourcemap: false, minify: false, logLevel: "info",
  external: ["better-sqlite3", "sharp", "7zip-bin", "node-unrar-js", "@img/*", "electron"],
  // CJS 依赖（fastify/avvio 等）被打进 ESM 后仍会 require('node:events')：用 createRequire 兜住
  banner: { js: '// AssetVault server bundle (generated by apps/desktop/build.mjs)\nimport { createRequire as __avCreateRequire } from "node:module";\nconst require = __avCreateRequire(import.meta.url);' },
});
// schema.sql 必须与 bundle 同目录：运行时用 new URL("./schema.sql", import.meta.url) 定位
copyFileSync(join(repoRoot, "apps", "server", "src", "db", "schema.sql"), join(here, "build", "schema.sql"));
console.log("server bundle -> apps/desktop/build/server.mjs (+ schema.sql)");
